name: "CI: macOS"

on: [ push, pull_request ]

env:
  CC: /usr/local/opt/llvm/bin/clang
  CXX: /usr/local/opt/llvm/bin/clang++
  VCPKG_COMMIT_ID: 70033dbb31527fb3e69654731f540f59c87787f9
  VCKPG_DEFAULT_TRIPLET: x64-tactile

jobs:
  macos-latest-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - name: Update packages
        shell: bash
        run: brew update

      - name: Install Ninja
        shell: bash
        run: brew install ninja

      - name: Install CMake
        shell: bash
        run: brew install cmake

      - name: Install LLVM
        shell: bash
        run: brew install llvm

      - name: Install GLFW
        shell: bash
        run: brew install glfw

      - name: Configure Vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: '${{env.VCPKG_COMMIT_ID}}'

      - name: Make Tactile triplet file available to Vcpkg
        shell: bash
        run: mv "${{github.workspace}}/cmake/x64-tactile.cmake" "${{github.workspace}}/vcpkg/triplets/community/x64-tactile.cmake"

      - name: Make build directory
        shell: bash
        run: mkdir build

      - name: Generate build files
        working-directory: ./build
        shell: bash
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vckpg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-tactile -GNinja

      - name: Build
        working-directory: ./build
        shell: bash
        run: ninja