name: "CI: macOS"

on: [ push, pull_request ]

jobs:
  macos-latest-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - name: Update packages
        shell: bash
        run: brew update

      - name: Install Ninja
        shell: bash
        run: brew install ninja

      - name: Install CMake
        shell: bash
        run: brew install cmake

      - name: Install LLVM
        shell: bash
        run: |
          brew install llvm
          export PATH=/usr/local/opt/llvm/bin:$PATH

      - name: Install mpg123
        shell: bash
        run: brew install mpg123

      - name: Install GLFW
        shell: bash
        run: brew install glfw

      - name: Install GLEW
        shell: bash
        run: brew install glew

      - name: Install Protobuf
        shell: bash
        run: brew install protobuf

      - name: Install SDL2
        shell: bash
        run: brew install SDL2

      - name: Install SDL2_image
        shell: bash
        run: brew install SDL2_image

      - name: Install SDL2_ttf
        shell: bash
        run: brew install SDL2_ttf

      - name: Make build directory
        shell: bash
        run: mkdir build

      - name: Generate build files
        working-directory: ./build
        shell: bash
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja

      - name: Build
        working-directory: ./build
        shell: bash
        run: ninja