name: "CI: macOS"

on: [ push ]

env:
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
  VCPKG_TARGET_TRIPLET: x64-osx
  VCPKG_CACHE_EDITION: 1

jobs:
  macos-latest-test:
    runs-on: macos-latest
    if: contains(github.event.head_commit.message, '[skip-ci]') == false
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          brew update
          brew install cmake
          brew install ninja
          brew install pkg-config
          brew install llvm

      - name: Cache Vcpkg
        id: restore-vcpkg-and-artifacts
        uses: actions/cache@v3
        with:
          path: |
            ${{env.VCPKG_ROOT}}
            !${{env.VCPKG_ROOT}}\buildtrees
            !${{env.VCPKG_ROOT}}\packages
            !${{env.VCPKG_ROOT}}\downloads
            !${{env.VCPKG_ROOT}}\installed
          key: tactile-macos-vcpkg-${{hashFiles('vcpkg.json')}}-${{env.VCPKG_CACHE_EDITION}}

      - name: Install Vcpkg
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/microsoft/vcpkg
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

      - name: Generate build files
        run: |
          mkdir build && cd build
          cmake .. -GNinja \
                   -DCMAKE_BUILD_TYPE=Debug \
                   -DCMAKE_C_COMPILER=$(brew --prefix llvm)/bin/clang \
                   -DCMAKE_CXX_COMPILER=$(brew --prefix llvm)/bin/clang++ \
                   -DVCPKG_TARGET_TRIPLET=${{env.VCPKG_TARGET_TRIPLET}} \
                   -DTACTILE_TREAT_WARNINGS_AS_ERRORS=ON

      - name: Build
        run: ninja -C build

      - name: Run tests
        working-directory: ./build/test
        run: ./TactileTests