name: "CI: Ubuntu"

on: [ push, pull_request ]

env:
  SDL_VIDEODRIVER: x11
  DISPLAY: :99.0
  VCPKG_COMMIT_ID: 70033dbb31527fb3e69654731f540f59c87787f9
  VCKPG_DEFAULT_TRIPLET: x64-tactile

jobs:
  ubuntu-latest-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: lukka/get-cmake@latest

      - name: Update packages
        shell: bash
        run: sudo apt update

      - name: Install graphics drivers
        shell: bash
        run: sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev libasound2-dev libpulse-dev

      - name: Install GCC 10
        shell: bash
        run: sudo apt install gcc-10 g++-10

      - name: Emulate video device
        shell: bash
        run: |
          sudo apt install xvfb
          /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX;
          sleep 3

      - name: Configure Vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: '${{env.VCPKG_COMMIT_ID}}'

      - name: Make Tactile triplet file available to Vcpkg
        shell: bash
        run: mv "${{github.workspace}}/cmake/x64-tactile.cmake" "${{github.workspace}}/vcpkg/triplets/community/x64-tactile.cmake"

      - name: Create build directory
        shell: bash
        run: mkdir -p build

      - name: Generate build files
        working-directory: ./build
        shell: bash
        env:
          CC: gcc-10
          CXX: g++-10
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vckpg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-tactile -GNinja

      - name: Build
        working-directory: ./build
        shell: bash
        env:
          CC: gcc-10
          CXX: g++-10
        run: ninja

      - name: Run tests
        working-directory: ./build/build
        shell: bash
        run: ./TactileTests