name: "CI: Windows"

on: [ push, pull_request ]

env:
  SDL_VERSION: 2.0.14
  IMG_VERSION: 2.0.5
  TTF_VERSION: 2.0.15
  GLEW_VERSION: 2.1.0

jobs:
  windows-latest-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: lukka/get-cmake@v3.18.3

      - name: Create binaries directory
        run: mkdir bin
        shell: cmd

      - name: Download SDL2
        uses: albin-johansson/download-sdl2@v1
        with:
          version: ${{env.SDL_VERSION}}
          sources_destination: .
          binaries_destination: bin

      - name: Download SDL2_image
        uses: albin-johansson/download-sdl2-image@v1
        with:
          version: ${{env.IMG_VERSION}}
          sources_destination: .
          binaries_destination: bin

      - name: Download SDL2_ttf
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-${{env.TTF_VERSION}}-VC.zip" `
                            -OutFile SDL2_ttf-devel-${{env.TTF_VERSION}}-VC.zip
          7z x -y SDL2_ttf-devel-${{env.TTF_VERSION}}-VC.zip

          mkdir bin
          Invoke-WebRequest -Uri "https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-${{env.TTF_VERSION}}-win32-x64.zip" `
                            -OutFile bin/SDL2_ttf-${{env.TTF_VERSION}}-win32-x64.zip


      - name: Download GLEW
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://sourceforge.net/projects/glew/files/glew/${{env.GLEW_VERSION}}/glew-${{env.GLEW_VERSION}}-win32.zip" `
                            -OutFile glew.zip `
                            -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::FireFox
          7z x -y glew.zip
          del glew.zip
          dir
          Copy-Item -Path glew-${{env.GLEW_VERSION}}/bin/Release/x64/glew32.dll `
                    -Destination bin/glew32.dll

      - name: Create build folder
        shell: cmd
        run: cmake -E make_directory ./build

      - name: Build
        working-directory: ./build
        shell: cmd
        env:
          SDL2DIR: ${{github.workspace}}/SDL2-${{env.SDL_VERSION}}
          SDL2IMAGEDIR: ${{github.workspace}}/SDL2_image-${{env.IMG_VERSION}}
          SDL2TTFDIR: ${{github.workspace}}/SDL2_ttf-${{env.TTF_VERSION}}
          GLEW_LIBRARIES: ${{github.workspace}}/glew-${{env.GLEW_VERSION}}/lib/Release/x64
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja
          ninja

      - name: Run tests
        working-directory: ./build/test
        shell: cmd
        run: TactileTests.exe