name: "CI: Windows"

on: [ push ]

env:
  VCPKG_ROOT: ${{github.workspace}}\vcpkg
  VCPKG_TARGET_TRIPLET: x64-windows-static-md
  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}\vcpkg\bincache
  VCPKG_CACHE_EDITION: 1

jobs:
  windows-latest-test:
    runs-on: windows-latest
    if: contains(github.event.head_commit.message, '[skip-ci]') == false
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1.11.0
      - uses: lukka/get-cmake@latest

      - name: Cache Vcpkg
        id: restore-vcpkg-and-artifacts
        uses: actions/cache@v3
        with:
          path: |
            ${{env.VCPKG_ROOT}}
            !${{env.VCPKG_ROOT}}\buildtrees
            !${{env.VCPKG_ROOT}}\packages
            !${{env.VCPKG_ROOT}}\downloads
            !${{env.VCPKG_ROOT}}\installed
          key: tactile-windows-vcpkg-${{hashFiles('vcpkg.json')}}-${{env.VCPKG_CACHE_EDITION}}

      - name: Install Vcpkg
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
          .\vcpkg\vcpkg integrate install

      - name: Create directory ${{env.VCPKG_DEFAULT_BINARY_CACHE}}
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        run: mkdir -p ${{env.VCPKG_DEFAULT_BINARY_CACHE}}

      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake .. -GNinja `
                   -DCMAKE_BUILD_TYPE=Debug `
                   -DVCPKG_TARGET_TRIPLET=${{env.VCPKG_TARGET_TRIPLET}} `
                   -DTACTILE_TREAT_WARNINGS_AS_ERRORS=ON

      - name: Build
        run: ninja -C build

      - name: Run tests
        working-directory: ./build/test
        shell: cmd
        run: TactileTests.exe