name: "CI: Windows"

on: [ push, pull_request ]

env:
  VCPKG_COMMIT_ID: 70033dbb31527fb3e69654731f540f59c87787f9

jobs:
  windows-latest-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: ilammy/msvc-dev-cmd@master
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: lukka/get-cmake@latest

      - name: Configure Vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: '${{env.VCPKG_COMMIT_ID}}'

      - name: Make Tactile triplet file available to Vcpkg
        shell: cmd
        run: copy "${{github.workspace}}\cmake\x64-tactile.cmake" "${{github.workspace}}\vcpkg\triplets\community\x64-tactile.cmake"

      - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
        uses: lukka/run-cmake@v10

      - name: Create build folder
        shell: cmd
        run: cmake -E make_directory ./build

      - name: Build
        working-directory: ./build
        shell: cmd
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-tactile -GNinja
          ninja

      - name: Run tests
        working-directory: ./build/build
        shell: cmd
        run: TactileTests.exe