name: "CI: Windows"

on: [ push, pull_request ]

env:
  VCPKG_ROOT: ${{github.workspace}}\vcpkg
  VCPKG_DEFAULT_TRIPLET: x64-windows-static
  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}\vcpkg\bincache
  VCPKG_COMMIT_ID: 70033dbb31527fb3e69654731f540f59c87787f9

jobs:
  windows-latest-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: ilammy/msvc-dev-cmd@master
      - uses: lukka/get-cmake@latest

      - name: Cache Vcpkg
        id: restore-vcpkg-and-artifacts
        uses: actions/cache@v2
        with:
          path: |
            ${{env.VCPKG_ROOT}}
            !${{env.VCPKG_ROOT}}\buildtrees
            !${{env.VCPKG_ROOT}}\packages
            !${{env.VCPKG_ROOT}}\downloads
            !${{env.VCPKG_ROOT}}\installed
          key: windows-${{env.VCPKG_COMMIT_ID}}-${{hashFiles('vcpkg.json')}}-x64-tactile-windows

      - name: Install Vcpkg
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat -disableMetrics

      - name: Create directory ${{env.VCPKG_DEFAULT_BINARY_CACHE}}
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        shell: powershell
        run: mkdir -p ${{env.VCPKG_DEFAULT_BINARY_CACHE}}

      - name: Make Tactile triplet file available to Vcpkg
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        working-directory: ./cmake
        shell: cmd
        run: copy "x64-tactile.cmake" "%VCPKG_ROOT%\triplets\community\x64-tactile.cmake"

      - name: Create build directory
        shell: cmd
        run: mkdir build

      - name: Generate build files
        working-directory: ./build
        shell: cmd
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug ^
                      -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}\scripts\buildsystems\vcpkg.cmake ^
                      -DVCPKG_TARGET_TRIPLET=x64-tactile ^
                      -GNinja

      - name: Build
        working-directory: ./build
        shell: cmd
        run: ninja

      - name: Run tests
        working-directory: ./build/build
        shell: cmd
        run: TactileTests.exe